@startuml

class AAUOC{

}

class Location{

}

class Event{

}

class Conference{

}

class BroadMeeting{

}

class Person{

}

class Member{

}

class BroadMember{

}

AAUOC o-- Event
AAUOC o-- Location
AAUOC o-- Person
Location -- Event
Event -- Member
Person -- Conference
Event <|-- Conference
Event <|-- BroadMeeting
Person <|-- Member
Member <|-- BroadMember

@enduml